zuul:
  routes:
    # /myProduct/product/list ->/product/product/list
    myProduct:
      path: /myProduct/**
      serviceId: product
  #排除指定路由
  ignored-patterns:
    - /**/product/listForOrder
  # 敏感标题
  sensitive-headers:
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 192.168.117.131
    port: 5672
    username: guest
    password: guest
