eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.117.129
    port: 5672
    username: guest
    password: guest
PRODUCT:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.RandomRule
